### ISSUE TITLE
Inserting custom fields via API

### ISSUE THREAD

**Issue by derstooge** [autopilotdev/autopilotdev.github.io#3]
Hi,
We inserted custom field via API - however they do not show up in the "manage custom fields" list and therefore the values stored in those custom fields can not be used to create smart segments.

When manually adding a custom field with the same label as the custom field was created via the API we can use it in for smart segmentation but the values are not linked to.

Any help?

**Comment by chrissharkey** [comment]
Hi derstooge,

This is a definite problem that we are working to address. This week we will be releasing an update which will automatically create custom fields when provided via API calls. Until now you've had to manually add them like the way you have. The fields are case sensitive so that is probably why you had trouble with them matching the values.

If you email me your company names and the field names to chris@autopilothq.com I will fix them up for you.

Chris.
