### ISSUE TITLE
[apiary] add a contact to a journey mock fails with an email address

### ISSUE THREAD

**Issue by samuelckaufman** [autopilotdev/autopilotdev.github.io#6]
http://docs.autopilot.apiary.io/#reference/api-methods/trigger-journey/add-a-contact-to-a-journey?console=1

When using email address in the request to the mock server for /v1/trigger/trigger_id/contact/contact_id_or_email
it throws an HTML error.

Expected: sending 'test@example.com' for contact_id_or_email should work
ex: /v1/trigger/004/contact/test@example.com
Actual: you get back an HTML error page

I haven't tested other endpoints much so I can't say if the parameter ':contact_id_or_email' isn't specified correctly or what.
Works fine in production, and was able to trigger a test journey :)

**Comment by chrissharkey** [comment]
Hi edibleenergy,

Thanks for this feedback. We mostly provide the mock endpoint since Apiary does it automatically. We have no ability to change the way their mocking server works so we can't really fix this. We are working on a major overhaul to our API and documentation and will be going with a different solution for it. Since we'll control the new one we will make sure that all examples work as documented.

Chris.
